---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-operator-mcp
  labels:
    app.kubernetes.io/name: flux-operator-mcp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-operator-mcp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flux-operator-mcp
    spec:
      serviceAccountName: flux-operator
      terminationGracePeriodSeconds: 10
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
             - matchExpressions:
               - key: kubernetes.io/os
                 operator: In
                 values:
                   - linux
      containers:
      - name: server
        image: flux-operator-mcp:latest
        imagePullPolicy: IfNotPresent
        args:
          - serve
          - --transport=sse
          - --port=8080
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - name: temp
            mountPath: /tmp
      volumes:
        - name: temp
          emptyDir: {}
