---
apiVersion: v1
kind: Service
metadata:
  name: flux-operator-mcp
  labels:
    app.kubernetes.io/name: flux-operator-mcp
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: flux-operator-mcp
